service: mongodb-triggers

variablesResolutionMode: 20210326

plugins:
  - serverless-stage-manager
  - serverless-plugin-warmup
  - serverless-disable-functions

custom:
  stages:
    - dev
    - test
    - staging
    - prod
  warmup:
    default:
      enabled: true
      prewarm: true
      timeout: 30
      name: ${self:provider.stage}-mongodb-triggers-warmer
      concurrency: ${self:custom.warmupConcurrency.${self:provider.stage}}
      role: ${opt:role, 'arn:aws:iam::044086777883:role/dataAnalyticsLambdaRole'}
  warmupConcurrency:
    dev: 1
    test: 1
    staging: 1
    prod: 10
  mongoHost:
    dev: dev-cluster.fg2e5.mongodb.net
    test: test-cluster.9mc2r.mongodb.net
    staging: stg-cluster-pl-0.7ljem.mongodb.net
    prod: prd-cluster-pl-0.5rvfa.mongodb.net
  mongoPassword:
    dev: ${ssm:dev-ds-mongodb-password}
    test: ${ssm:test-ds-mongodb-password}
    staging: ${ssm:staging-ds-mongodb-password}
    prod: ${ssm:prod-ds-mongodb-password}
  securityGroupIds:
    dev:
      - sg-0a85d287510c750fb
    test:
      - sg-0821f0b9421d5c942
    staging:
      - sg-0a676a88fdcd07038
    prod:
      - sg-02f9c88c7e05b1f05
  subnetIds:
    dev:
      - subnet-06dd909aac8fd1948
    test:
      - subnet-090044e7a4daccd43
    staging:
      - subnet-07a1a18b1527f00c7
      - subnet-0587b148568217c70
    prod:
      - subnet-0290592d406bccc27
      - subnet-0790d32929fd45c33
  topicClassifyEventBus:
    dev: 616af95670473219e6dcabd0
    test: 619b653f5eed5334ed0cf454
    staging: 6197e7e47c52acf715643c77
    prod: 619b67a86d52a17958345276

provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 900
  stackName: ${self:provider.stage}-mongodb-triggers
  logRetentionInDays: 14
  deploymentBucket:
    name: castcle-data-analytics
  iam:
    role: ${opt:role, 'arn:aws:iam::044086777883:role/dataAnalyticsLambdaRole'}
  vpc:
    securityGroupIds: ${self:custom.securityGroupIds.${self:provider.stage}}
    subnetIds: ${self:custom.subnetIds.${self:provider.stage}}
  eventBridge:
    useCloudFormation: true
  ecr:
    images:
      app_image:
        uri: REPOSITORY_URI@DIGEST
  environment:
    ENV: ${self:provider.stage}
    MONGO_HOST: ${self:custom.mongoHost.${self:provider.stage}}
    MONGO_PASSWORD: ${self:custom.mongoPassword.${self:provider.stage}}

functions:
  contentStatsUpdate:
    name: ${self:provider.stage}-mongodb-trigger-content-stats-update
    memorySize: 1024
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - content_stats_update.handle
    events:
      - schedule: cron(*/15 * * * ? *)
  creatorStatsUpdate:
    name: ${self:provider.stage}-mongodb-trigger-creator-stats-update
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - creator_stats_update.handle
    events:
      - schedule: cron(23 * * * ? *)
  hashtagStatsUpdate:
    name: ${self:provider.stage}-mongodb-trigger-hashtag-stats-update
    enabled: false
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - hashtag_stats_update.handle
    events:
      - schedule: cron(0 0 1 1 ? 1970)
  topicClassification:
    name: ${self:provider.stage}-mongodb-trigger-topic-classification
    memorySize: 512
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - topic_classification.handle
    events:
      - eventBridge:
          eventBus: arn:aws:events:us-east-1:044086777883:event-bus/aws.partner/mongodb.com/stitch.trigger/${self:custom.topicClassifyEventBus.${self:provider.stage}}
          pattern:
            account:
              - "044086777883"
  personalizeContentTrainer:
    name: ${self:provider.stage}-mongodb-trigger-personalize-content-trainer
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - personalize_content_trainer.handle
    events:
      - schedule: cron(25 * * * ? *)

  coldStartTrainer:
    name: ${self:provider.stage}-mongodb-trigger-coldstart-trainer
    memorySize: 2048
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - coldstart_trainer.handle
    events:
      - schedule: cron(25 * * * ? *)
  perCtTrainer:
    name: ${self:provider.stage}-mongodb-trigger-per-ct-trainer
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - per_ct_trainer.handle
    events:
      - schedule: cron(0 7 * * ? *)

  userEngagementStatUpdate:
    name: ${self:provider.stage}-mongodb-trigger-user-engagement-stat-update
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - user_engagement_stats_update.handle
    events:
      - schedule: cron(22 * * * ? *)

  userClassifyTrainer:
    name: ${self:provider.stage}-mongodb-trigger-user-classify-trainer
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - user_classify_trainer.handle
    events:
      - schedule: cron(0 * * * ? *)

#fraudDetection
  credentialFeaturesUpdate:
    name: ${self:provider.stage}-mongodb-trigger-credential-features-update
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - credential_features_update.handle
    events:
      - schedule: cron(*/5 * * * ? *)

    fraudDetectionPredictor:
    name: ${self:provider.stage}-mongodb-trigger-fraud-detection-predictor
    memorySize: 1024
    warmup:
      default:
        enabled: false
    image:
      name: app_image
      command:
        - fraud_detection_predictor.handle
    events:
      - eventBridge:
          eventBus: arn:aws:events:us-east-1:044086777883:event-bus/aws.partner/mongodb.com/stitch.trigger/${self:custom.fraudDetectionPredictorEventBus.${self:provider.stage}}
          pattern:
            account:
              - "044086777883"